### ISSUE TITLE
ImportError: cannot import name 'PositionNet' from 'diffusers.models.embeddings' 

### ISSUE THREAD

**Issue by huanggou666** [BadToBest/EchoMimic#10]
(echomimic) C:\ALLWEBUI\EchoMimic\EchoMimic>python -u infer_audio2vid.py
Traceback (most recent call last):
  File "infer_audio2vid.py", line 23, in <module>
    from src.models.unet_2d_condition import UNet2DConditionModel
  File "C:\ALLWEBUI\EchoMimic\EchoMimic\src\models\unet_2d_condition.py", line 18, in <module>
    from diffusers.models.embeddings import (
ImportError: cannot import name 'PositionNet' from 'diffusers.models.embeddings' (C:\Users\admin\.conda\envs\echomimic\lib\site-packages\diffusers\models\embeddings.py)

**Comment by farhanyosuf11** [comment]
I fixed it by installing diffusers=0.24.0

**Comment by huanggou666** [comment]
> I fixed it by installing diffusers=0.24.0

thanks problem solved
