### ISSUE TITLE
Full body talking video?

### ISSUE THREAD

**Issue by moxiegushi** [BadToBest/EchoMimic#109]
Thanks for your great work!  May I ask do you have any plans on something  like "full body talking video"  instead of talking head?

**Comment by oisilener1982** [comment]
i also need this

**Comment by lymhust** [comment]
next work echomimic-v2 will focus on halfbody generation.

**Comment by oisilener1982** [comment]
> next work echomimic-v2 will focus on halfbody generation.

Will this be released this year?
