### ISSUE TITLE
Any way to prevent the image crop?

### ISSUE THREAD

**Issue by farhanyosuf11** [BadToBest/EchoMimic#11]
Hi
Great work! One of the best I have tried in comparison to Sadtalker, Hallo, Musepose etc.
I just want to know if there’s way to get the video with the same features as the input image (without cropping into the face)?
Thanks for open sourcing :)

**Comment by yuange250** [comment]
the easiest way is increase the args.facecrop_dilation_ratio, like 1.0, 2.0

or delete the followed codes in infer_audio2vid.py:
![image](https://github.com/BadToBest/EchoMimic/assets/11451501/c4ecba6d-ee43-498d-ad1b-339f6b140060)

**Comment by cacard** [comment]
> the easiest way is increase the args.facecrop_dilation_ratio, like 1.0, 2.0
> 
> or delete the followed codes in infer_audio2vid.py: ![image](https://private-user-images.githubusercontent.com/11451501/347657158-c4ecba6d-ee43-498d-ad1b-339f6b140060.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MDg0MTMsIm5iZiI6MTcyMjkwODExMywicGF0aCI6Ii8xMTQ1MTUwMS8zNDc2NTcxNTgtYzRlY2JhNmQtZWU0My00OThkLWFkMWItMzM5ZjZiMTQwMDYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDAxMzUxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyMDcxNzgxM2UwYTZjYzhkODVjM2M2Yzg5Zjg4ZjkyNTcyNmEzM2ZiMTNiYjRkYmE0MWI0NmJmZTNjM2M2MTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kLllX2axVedtWdo-MsLpp_0vKm8nUdLDD3P6i1htwXA)

Will your actions affect the final outcome.
