### ISSUE TITLE
diffusers版本问题

### ISSUE THREAD

**Issue by yeohx** [BadToBest/EchoMimic#113]
我使用 diffusers==0.26.1 报错:cannot import name ‘PositionNet‘ from ‘diffusers.models.embeddings

降级到 diffusers==0.25.1 报错:cannot import name 'CaptionProjection' from 'diffusers.models.embeddings' (/root/miniconda3/lib/python3.10/site-packages/diffusers/models/embeddings.py) 

我猜测可能是我其他依赖有版本问题.是否可以提供一下各个依赖包的版本

**Comment by XingWang1234** [comment]
`requirements.txt` requires  diffusers=0.24.0, I installed this version, and it works

**Comment by yeohx** [comment]
> `requirements.txt` requires diffusers=0.24.0, I installed this version, and it works

请问一下,你的centos和python是什么版本的?

**Comment by XingWang1234** [comment]
> > `requirements.txt` requires diffusers=0.24.0, I installed this version, and it works
> 
> 请问一下,你的centos和python是什么版本的?

my OS is linux: PRETTY_NAME="Ubuntu 22.04.4 LTS"
python==3.10
