### ISSUE TITLE
Is this suitable for lipsync?

### ISSUE THREAD

**Issue by xiankgx** [BadToBest/EchoMimic#14]
Hi, this project seems to be animating a reference image with driving audio and/or face pose. Is this suitable for lipsync?

Also, this seems to be using video diffusion methods, how do you make it to generate such a long video, without running into resource constraints? Is this using Conv method instead of temporal attention for handling the temporal dimension?

**Comment by huanggou666** [comment]
it is renders kind of slow, don't think people can use it for lipsync, 5 second audio on RTX 4090 , takes 30/30 [03:37<00:00,  7.25s/it]

**Comment by xiankgx** [comment]
It will be slow because this is based on video diffusion model. Not looking at realtime prediction. But it is suitable for lip sync? Do you have a pipeline for that? 

How can we split the audio feature to only generate one frame, rather than complete video to do frame-by-frame processing?

**Comment by JoeFannie** [comment]
It is a common limitation for SD models for its slow inference. We are trying to accelerate it by step distillation techniques. It is possible that we release a fast version of EchoMimic in this month.
