### ISSUE TITLE
CUDA out of memory. :( no hugging face no colab 

### ISSUE THREAD

**Issue by medalawi** [BadToBest/EchoMimic#141]
“First, thank you for sharing this wonderful repository. 
-How to avoid cuda out of memory many repos has an option  to set batch size how to set it in echomimic?
**Could you please create a lite version for users with lower-end graphic cards?** 
-Additionally, Hugging Face closed the session before EchoMimic completed due to GPU time limits. 
-I tried using Google Colab but encountered a size limit while downloading the pretrained model, as there wasn’t enough space.”

**Comment by nitinmukesh** [comment]
duration of audio?

**Comment by medalawi** [comment]
Cuda out of memory show in terminal before  it run in browser
I tried huggingface with 2sec got GPU abort time limit

**Comment by nitinmukesh** [comment]
I am not sure why CUDA OOM error.

What is you PC specification? GPU / VRAM / RAM.

I just now converted 56s audio on RTX 4060 8 GB VRAM, it took a lot of time but no OOM issues
