### ISSUE TITLE
Train code Release?

### ISSUE THREAD

**Issue by zdyshine** [BadToBest/EchoMimic#16]
Congrats on this great work!! When will the train code be released? Thanks!

**Comment by JoeFannie** [comment]
We are considering to release the training code. However, we are occupied with many other TODOs such as inference acceleration, paper writing and so on. The training code release is not on the top. It may not be released soon.

**Comment by nitinmukesh** [comment]
@JoeFannie 

The results are just amazing. Any possibility to prioritize training release so we can train in other languages. It will be helpful to use with other languages.
