### ISSUE TITLE
照片可以为全身照吗

### ISSUE THREAD

**Issue by chenhongwu127** [BadToBest/EchoMimic#17]
刚体验了下，照片为半身照的，效果还行，echomimic支持照片为全身照的吗？

**Comment by yuange250** [comment]
直接把全身图扔给SD这个还不太行。。。。要不可以自己调整下裁剪代码加一个贴回的操作？

**Comment by JoeFannie** [comment]
目前只支持人脸区域的输入，所以全身图需要调整下，crop人脸区域输入
