### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by opchronatron** [BadToBest/EchoMimic#2]
what is the inference time per frame on a low/mid level card?

**Comment by yuange250** [comment]
However, the time consumption is a biased statistical measure. It is not only affected by GPU performance but also significantly influenced by CPU, memory, and disk I/O, among other factors.

**Comment by yuange250** [comment]
The time consumption is a biased statistical measure. It is not only affected by GPU performance but also significantly influenced by CPU, memory, and disk I/O, among other factors.
