### ISSUE TITLE
运行    python -u infer_audio2vid.py 出现错误 ImportError: cannot import name 'PositionNet' from 'diffusers.models.embeddings' (

### ISSUE THREAD

**Issue by anstonjie** [BadToBest/EchoMimic#20]
Traceback (most recent call last):
  File "E:\ai3\EchoMimic\infer_audio2vid.py", line 23, in <module>
    from src.models.unet_2d_condition import UNet2DConditionModel
  File "E:\ai3\EchoMimic\src\models\unet_2d_condition.py", line 18, in <module>
    from diffusers.models.embeddings import (
ImportError: cannot import name 'PositionNet' from 'diffusers.models.embeddings' (E:\ai3\EchoMimic\venv\Lib\site-packages\diffusers\models\embeddings.py)

**Comment by yuange250** [comment]
pip install diffusers==0.24.0

**Comment by anstonjie** [comment]
thank you
