### ISSUE TITLE
How can I solve this error?

### ISSUE THREAD

**Issue by z497947607** [BadToBest/EchoMimic#21]
Traceback (most recent call last):
  File "/home/tom/fssd/EchoMimic/infer_audio2vid.py", line 23, in <module>
    from src.models.unet_2d_condition import UNet2DConditionModel
  File "/home/tom/fssd/EchoMimic/src/models/unet_2d_condition.py", line 18, in <module>
    from diffusers.models.embeddings import (
ImportError: cannot import name 'PositionNet' from 'diffusers.models.embeddings' (/opt/conda/lib/python3.10/site-packages/diffusers/models/embeddings.py)

**Comment by yuange250** [comment]
pip install diffusers==0.24.0

**Comment by z497947607** [comment]
谢谢，但是又出现了ffmpeg的报错，是因为我放的路径不对吗
Traceback (most recent call last):
  File "/home/tom/fssd/EchoMimic/infer_audio2vid.py", line 25, in <module>
    from src.models.whisper.audio2feature import load_audio_model
  File "/home/tom/fssd/EchoMimic/src/models/whisper/audio2feature.py", line 2, in <module>
    from .whisper import load_model
  File "/home/tom/fssd/EchoMimic/src/models/whisper/whisper/__init__.py", line 11, in <module>
    from .audio import load_audio, log_mel_spectrogram, pad_or_trim
  File "/home/tom/fssd/EchoMimic/src/models/whisper/whisper/audio.py", line 5, in <module>
    import ffmpeg
ModuleNotFoundError: No module named 'ffmpeg'

**Comment by yuange250** [comment]
没事，直接把infer_audio2vid.py里的ffmpeg_path = os.getenv('FFMPEG_PATH')

**Comment by yuange250** [comment]
注意有时候tar解压文件夹容易多解压出一层文件夹

**Comment by z497947607** [comment]
谢谢，已经解决了，原来是压缩了两遍，第一次解压出来是个tar压缩包，还需要在解压一次

**Comment by nitinmukesh** [comment]
@yuange250 

I am getting this error

In infer_audio2vid.py
ffmpeg_path = os.getenv('FFMPEG_PATH')

C:\sd>echo %FFMPEG_PATH%
C:\sd\ffmpeg-4.4-amd64-static

Still I see this error

```
(echomimic) C:\tut\EchoMimic>python infer_audio2vid.py
C:\Users\nitin\miniconda3\envs\echomimic\lib\site-packages\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
C:\Users\nitin\miniconda3\envs\echomimic\lib\site-packages\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
add ffmpeg to path
```
