### ISSUE TITLE
add ffmpeg to path

### ISSUE THREAD

**Issue by nitinmukesh** [BadToBest/EchoMimic#23]
I am getting this error

In infer_audio2vid.py
`ffmpeg_path = os.getenv('FFMPEG_PATH')`

```
C:\sd>echo %FFMPEG_PATH%
C:\sd\ffmpeg-4.4-amd64-static
```

Still I see this error

```
(echomimic) C:\tut\EchoMimic>python infer_audio2vid.py
C:\Users\nitin\miniconda3\envs\echomimic\lib\site-packages\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
C:\Users\nitin\miniconda3\envs\echomimic\lib\site-packages\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
add ffmpeg to path
```

**Comment by kesyn** [comment]
I looked at the code where this message appears. If you see the log message "add ffmpeg to path," it means that FFMPEG_PATH has been found. The code will automatically add FFMPEG_PATH to the PATH environment variable. If FFMPEG_PATH is not set correctly, you will see the message "please download ffmpeg-static and export to FFMPEG_PATH. For example: export FFMPEG_PATH=/musetalk/ffmpeg-4.4-amd64-static". Seeing "add ffmpeg to path" means it has been successfully found and the program is ready to run.

**Comment by yuange250** [comment]
Typically, this issue occurs because the decompression software has extracted an extra layer of folders.😂

**Comment by nitinmukesh** [comment]
> Typically, this issue occurs because the decompression software has extracted an extra layer of folders.😂

This may not be true

<img width="551" alt="image" src="https://github.com/user-attachments/assets/15c96311-5f70-4f46-95dc-6cd70ca0b974">

**Comment by nitinmukesh** [comment]
> I looked at the code where this message appears. If you see the log message "add ffmpeg to path," it means that FFMPEG_PATH has been found. The code will automatically add FFMPEG_PATH to the PATH environment variable. If FFMPEG_PATH is not set correctly, you will see the message "please download ffmpeg-static and export to FFMPEG_PATH. For example: export FFMPEG_PATH=/musetalk/ffmpeg-4.4-amd64-static". Seeing "add ffmpeg to path" means it has been successfully found and the program is ready to run.

Thank you for the explanation. So this is not an issue.
