### ISSUE TITLE
supports Russian speech 

### ISSUE THREAD

**Issue by enjoykian** [BadToBest/EchoMimic#24]
Hello and thanks for this wonderful work

Please tell me, before installing I would like to know if this works with Russian voice acting?

PS: sorry for my english

**Comment by yuange250** [comment]
We indeed have not trained our model with Russian data, but algorithms like lipsync generally have strong cross-language generalization capabilities. For instance, while the performance on Japanese may not be as good as on Chinese or English, it can still achieve certain effects, so it's worth giving it a try. And your English is quite good :)
