### ISSUE TITLE
Slow Inference

### ISSUE THREAD

**Issue by thanhhung0112** [BadToBest/EchoMimic#27]
I followed the instructions in README.md and run it on Colab, but the elapsed time per timestep is about 3 minutes, the length of the audio is 19 seconds, have you ever tested on Colab?

**Comment by nitinmukesh** [comment]
@Mengjintao 

How do you generate calling graph. I am not technical.

**Comment by yuange250** [comment]
Very brilliant work,  the accelerated model is still training, maybe it will takes several weeks to optimize to get a better effet, and we will inform you as the accelerated model is released.


> I run "python -u infer_audio2vid.py --steps=10" on RTX 4090 and A100-80G with one audio file (chunnnuanhuakai.wav) and one image (b.png), it takes 3m6s and 3m31s respectively. The accelerate(https://pypi.org/project/accelerate/) package has already been installed.
> 
> I also profiled the inference process, the calling graph is attached. I found that the bottleneck is the following three functions: unet_3d_blocks, unet_3d_cho, mutual_self_attention.hacked_basic_transformer_inner_forward. ![mine](https://private-user-images.githubusercontent.com/4187849/348158985-0dbb23cd-10f5-4e7b-91e4-a87fcc3c8d2a.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5MzMyMjgsIm5iZiI6MTcyMDkzMjkyOCwicGF0aCI6Ii80MTg3ODQ5LzM0ODE1ODk4NS0wZGJiMjNjZC0xMGY1LTRlN2ItOTFlNC1hODdmY2MzYzhkMmEuc3ZnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTRUMDQ1NTI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWM3OGY0YzMyYjA0ZGNjNDdiMzYzNGZjMjQ3YjI3NTUwZjcyZjU2YzlhMTE2ZGFkMGE3MmFmOWIzOGNmNjg0NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.yri-0E62-YImpHF76HIxiFvOirCJHctC5qi8rHHI6cg)
> 
> I found you have the plan to release Accelerated models, can you given us a timeline for that?
> 
> Currently, do you have some suggestions for me to accelerate the whole pipeline?

**Comment by yuange250** [comment]
> Very brilliant work, the accelerated model is still under training, maybe it will takes several weeks to optimize to get a better effet, and we will inform you as the accelerated model is released.
> 
> > I run "python -u infer_audio2vid.py --steps=10" on RTX 4090 and A100-80G with one audio file (chunnnuanhuakai.wav) and one image (b.png), it takes 3m6s and 3m31s respectively. The accelerate(https://pypi.org/project/accelerate/) package has already been installed.
> > I also profiled the inference process, the calling graph is attached. I found that the bottleneck is the following three functions: unet_3d_blocks, unet_3d_cho, mutual_self_attention.hacked_basic_transformer_inner_forward. ![mine](https://private-user-images.githubusercontent.com/4187849/348158985-0dbb23cd-10f5-4e7b-91e4-a87fcc3c8d2a.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5MzMyMjgsIm5iZiI6MTcyMDkzMjkyOCwicGF0aCI6Ii80MTg3ODQ5LzM0ODE1ODk4NS0wZGJiMjNjZC0xMGY1LTRlN2ItOTFlNC1hODdmY2MzYzhkMmEuc3ZnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTRUMDQ1NTI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWM3OGY0YzMyYjA0ZGNjNDdiMzYzNGZjMjQ3YjI3NTUwZjcyZjU2YzlhMTE2ZGFkMGE3MmFmOWIzOGNmNjg0NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.yri-0E62-YImpHF76HIxiFvOirCJHctC5qi8rHHI6cg)
> > I found you have the plan to release Accelerated models, can you given us a timeline for that?
> > Currently, do you have some suggestions for me to accelerate the whole pipeline?

**Comment by JoeFannie** [comment]
We have released our accelerated models and pipe. You can have a try now!

**Comment by 0xbok** [comment]
@JoeFannie is the accelerated model released only for the pose version?

**Comment by Mengjintao** [comment]
How can we test it with your released accelerated models?
