### ISSUE TITLE
ImportError: cannot import name 'PositionNet' from 'diffusers.models.embeddings'

### ISSUE THREAD

**Issue by oisilener1982** [BadToBest/EchoMimic#3]
(echomimic) D:\AI\EchoMimic>python -u infer_audio2vid.py
Traceback (most recent call last):
  File "infer_audio2vid.py", line 23, in <module>
    from src.models.unet_2d_condition import UNet2DConditionModel
  File "D:\AI\EchoMimic\src\models\unet_2d_condition.py", line 18, in <module>
    from diffusers.models.embeddings import (
ImportError: cannot import name 'PositionNet' from 'diffusers.models.embeddings' (C:\Users\Renel\anaconda3\envs\echomimic\lib\site-packages\diffusers\models\embeddings.py)

**Comment by yuange250** [comment]
Upgrading the 'diffusers' to higher version may solve the problem, try:
pip install diffusers==0.24.0

**Comment by oisilener1982** [comment]
thanks it solved the issue

**Comment by lonngxiang** [comment]
一样错误
