### ISSUE TITLE
Those who are having issues installing EchoMimic

### ISSUE THREAD

**Issue by oisilener1982** [BadToBest/EchoMimic#31]
This is the best talking avatar that I have ever used, but it takes 7 minutes for a 5-second video in 3080.  I gave up trying to install this, but now it is working. This is way better than Hedra and LivePortrait.

I even asked for help here and i still got so many errors with no solution. Thank you so much for this tutorial. below

https://www.youtube.com/watch?v=WtHdvSSQlWo

**Comment by yuange250** [comment]
Thanks for your contribution!

**Comment by nitinmukesh** [comment]
@yuange250 
I agree this is the best talking head so far. Thanks to all the developers for making it available.
The only point where it need improvement is duration of processing. Once that is done it will be awesome.

**Comment by nitinmukesh** [comment]
@yuange250 

Kindly update the link of video as earlier video is removed and new video posted to include the changes .

New video link
https://www.youtube.com/watch?v=WtHdvSSQlWo

<img width="776" alt="image" src="https://github.com/user-attachments/assets/1eb5ee70-6b7d-4ace-911f-84603b37ea2b">

**Comment by yuange250** [comment]
Thanks for your advice, efficiency optimization is the most emergent thing we are working on.

**Comment by oisilener1982** [comment]
> Thanks for your advice, efficiency optimization is the most emergent thing we are working on.

THe link is broken for the Video Installation tutorial
