### ISSUE TITLE
The image stops moving after 48 seconds

### ISSUE THREAD

**Issue by DannyWu25** [BadToBest/EchoMimic#33]
Is the maximum length only 48 seconds? If it exceeds 48 seconds, the image will stop moving.

**Comment by oisilener1982** [comment]
Not sure if this will solve your problem but you can try to use gradio and adjust the length

**Comment by DannyWu25** [comment]
> Not sure if this will solve your problem but you can try to use gradio and adjust the length

It's working,thanks a lot
