### ISSUE TITLE
生成帧率过高？

### ISSUE THREAD

**Issue by smthemex** [BadToBest/EchoMimic#34]
![frame](https://github.com/user-attachments/assets/125594d5-3d32-429a-8eeb-fe16e2ac1904)
感谢你们的开源，我制作了基于你们的方法的comfyUI插件，但是在默认24帧的帧率下，使用默认的方法，无论是保存图片，还是输出的人物图片（我改成串流输出再后期合成），二者均发现帧率过高，我要调整到12的fps才能让人物的动作变得自然，但是这样带来的效果是，没有了24帧的流程度。

**Comment by smthemex** [comment]
补充一下，如果启用降噪模型，反而帧率正常了。

**Comment by yuange250** [comment]
有没有效果之类的呀，可以加主页的微信群一起交流一下～感谢你的开发工作～

**Comment by smthemex** [comment]
有，迟点我会上传代码，并在B站发布。
