### ISSUE TITLE
Bugs found

### ISSUE THREAD

**Issue by westNeighbor** [BadToBest/EchoMimic#35]
Here are things that probably stopping you from running as same for me. Hope it can help you if meeting same problems. 
1. I am using Windows and Python 3.10.11. The latest torch version (2.3.0) won't work, but previous version 2.2.2 is okay, to install the previous versions check [torch installation](https://pytorch.org/get-started/previous-versions/), e.g. `pip install torch==2.2.2 torchvision==0.17.2 torchaudio==2.2.2 --index-url https://download.pytorch.org/whl/cu121`
2. To use pose reference, the mediapipe package needed to be installed `pip install mediapipe`
3. The file name `denoising_unet-pose.pth` needs to be renamed to `denoising_unet_pose.pth`

The first two can be fixed by modifying the `requirements.txt` file as follows:
>torch>=2.0.1,<=2.2.2
torchvision>=0.15.2,<=0.17.2
torchaudio>=2.0.2,<=2.2.2
mediapipe
transformers>=4.38.2
diffusers==0.24.0
torchmetrics
torchtyping
tqdm
ffmpeg-python==0.2.0
facenet_pytorch==2.5.0
moviepy==1.0.3
einops==0.4.1
omegaconf==2.3.0
opencv-python
av==11.0.0
gradio

Hope the authors can fix them 🔜

**Comment by yuange250** [comment]
Thanks a lot !!

**Comment by yuange250** [comment]
Those bugs was fixed according to your advice, thanks for your conrtibution!

**Comment by nitinmukesh** [comment]
@westNeighbor 

Did pose reference worked for you?
 It's not working for me, any suggestions
https://github.com/BadToBest/EchoMimic/issues/36

**Comment by westNeighbor** [comment]
My runs okay. How can I suggest without any error info?
