### ISSUE TITLE
Comfyui nodes? and safetensors?

### ISSUE THREAD

**Issue by GamingDaveUk** [BadToBest/EchoMimic#4]
Are there any comfyui nodes for this and are there safetensor versions of the models used? In this day and age we have to be so careful with models, been a fair few bad actors in the ai community.
On paper this really does look like the answer to my prayers. I have a ton of audio files that i need to get an avatar to speak (single image) for a project I am working on. He is a story teller and Bio reader for our guild. all the nodes I have looked at so far need a video to drive the animation, somewhat defeating the purpose) or not installable.

**Comment by yuange250** [comment]
Thank you for your valuable suggestion. Developing ComfyUI nodes will indeed allow more people who need this technology to enjoy its convenience. We will proceed with the development of related ComfyUI nodes as soon as possible. However, as we lack experience in developing ComfyUI nodes, the development timeline might be longer than expected. We hope you can patiently wait.

**Comment by GamingDaveUk** [comment]
> Thank you for your valuable suggestion. Developing ComfyUI nodes will indeed allow more people who need this technology to enjoy its convenience. We will proceed with the development of related ComfyUI nodes as soon as possible. However, as we lack experience in developing ComfyUI nodes, the development timeline might be longer than expected. We hope you can patiently wait.

Happy to wait, just knowing there is going to be a comfyui node is a good thing. its even possible the community may beat you to the making of the node. There is nothing like this (Currently using a app called "crazytalk 8" from 2019, now discontinued and its so not as good as I remember. 

Will wait patiently....semi patiently perhaps lol.... for the node and wish you luck with its development. It will be a good addition to Comfyui, not just to bring it to more people but will allow us to do even more with it.

If your not familiar with comfyui the node based workflow would allow, for example, the end video created by your process to then go off into the workflow to have the frames seperated and upscaled, or outpainted etc (just be sure to have a video file output on the node that does the work :) ) The community will make amazing things with this as a node :) 

Thank you for the reply, and thank you for being opensource.

**Comment by yuange250** [comment]
> > Thank you for your valuable suggestion. Developing ComfyUI nodes will indeed allow more people who need this technology to enjoy its convenience. We will proceed with the development of related ComfyUI nodes as soon as possible. However, as we lack experience in developing ComfyUI nodes, the development timeline might be longer than expected. We hope you can patiently wait.
> 
> Happy to wait, just knowing there is going to be a comfyui node is a good thing. its even possible the community may beat you to the making of the node. There is nothing like this (Currently using a app called "crazytalk 8" from 2019, now discontinued and its so not as good as I remember.
> 
> Will wait patiently....semi patiently perhaps lol.... for the node and wish you luck with its development. It will be a good addition to Comfyui, not just to bring it to more people but will allow us to do even more with it.
> 
> If your not familiar with comfyui the node based workflow would allow, for example, the end video created by your process to then go off into the workflow to have the frames seperated and upscaled, or outpainted etc (just be sure to have a video file output on the node that does the work :) ) The community will make amazing things with this as a node :)
> 
> Thank you for the reply, and thank you for being opensource.

We will keep this issue open until the node development is completed, and we will immediately notify you once the node development is finished. :)

**Comment by shivshankar11** [comment]
models are prunable? fp8 version? can it run faster with tensorrt/stable_fast/lcm/tcd/turbo/lighting loras?

**Comment by yuange250** [comment]
We are pleased to tell you that ComfyUI version EchoMimic was provided by @smthemex at https://github.com/smthemex/ComfyUI_EchoMimic , enjoy it:)

**Comment by GamingDaveUk** [comment]
Can you confirm if the output here is due to the early nature of echomimic or an error with the node... or well...my error?
https://github.com/smthemex/ComfyUI_EchoMimic/issues/5
The lipsyncing didnt seem to go well and it only did 5 seconds of audio (took a minute per second on my rtx 3090 so for 289 second clip (4 minutes 49 seconds) that would be 289 minutes or 4 hours and 49 minutes... that doesnt seem right lol

**Comment by shivshankar11** [comment]
100 frame length will get you 4 seconds, this lipsync model is very demanding, you can try sadtalker for for significantly faster but lower quality lipsync

**Comment by GamingDaveUk** [comment]
> 100 frame length will get you 4 seconds, this lipsync model is very demanding, you can try sadtalker for for significantly faster but lower quality lipsync

From what I can see Sadtalker is an abandoned project.
I fed it this a 4 minute 49 second audio file so assumed it would use the full file. Not sure why it only used the first 5 seconds. However the speed is so slow that it would be impractical at its current state to use. about 5 hours of 100% gpu usage on a 3090.... not good. 
Hopefully the code will get better with time., from what I can see this is still new. 

On the lipsync, that wasnt good for this video, though 5 seconds is not much time to make a judgement on. 

For me this may be something to look back in on in a month or so if its just a case of the code isnt ready yet.
