### ISSUE TITLE
Pink Artifacts Around Image in Video Rendering

### ISSUE THREAD

**Issue by Galleons2029** [BadToBest/EchoMimic#40]
**Description:**
I am experiencing an issue with video rendering where pink artifacts appear around the images. This happens when I use a specific image to generate a video. The pink color appears prominently around the edges of the image, causing an unwanted visual effect.

**Steps to Reproduce:**
1. Use the attached image and audio as input.
2. Generate a video using the standard rendering settings.
3. Observe the pink artifacts around the edges of the image in the output video.

**Expected Behavior:**
The image should appear in the video without any pink artifacts or unwanted colors around the edges.

**Actual Behavior:**
The image is rendered with pink artifacts around the edges, which affects the visual quality of the video.

**Attachments:**
1. Input Image
<img src="https://github.com/user-attachments/assets/5a89eea5-93b0-4a20-952a-bf52544ca2b9" alt="test1" width="300"/>

2. Output Video with Pink Artifacts

https://github.com/user-attachments/assets/5fad609e-6b2c-4f14-bab4-c7ee6866daf1

**Environment:**
- Operating System: Ubuntu 22.04.4 LTS
- CUDA 12.2
- A100 80G
- python=3.11.9

**Additional Information:**
- I have verified that the input image does not have any transparent or pink regions.
- This issue occurs consistently with this image with a white background but not for sure to others.

**Potential Solutions:**
- Ensuring the input image has a solid background without transparency.
- Checking and adjusting the video encoding settings to handle color space correctly.
- Preprocessing the image to eliminate any edge effects before rendering.

Any assistance or guidance on how to resolve this issue would be greatly appreciated. Thank you!

---

**Comment by yuange250** [comment]
有可能是这里引入的：

**Comment by Galleons2029** [comment]
效果明显有提升，但稍有残余

https://github.com/user-attachments/assets/f93115fb-4044-4ef3-bc4d-d20287fbac26

之后又试了几组样本，在纯白背景下效果相同

**Comment by yuange250** [comment]
> 效果明显有提升，但稍有残余
> 
>  output_video_with_audio.2.mp4 
> 之后又试了几组样本，在纯白背景下效果相同
嗯嗯，背景有artifacts也是意料之中的，因为训练数据里很少有纯白背景。。。我加的clamp代码主要为了适应网友们千奇百怪的输入，如果你的测试图质量都这么高，那不用加那行代码

**Comment by Galleons2029** [comment]
感谢指导，另外，我尝试了不同参数下的Facecrop Dilation Ratio和Height都没有获得完整的头部人像（如上图，头顶部分被截取），请问该如何复现出demo上的效果？

**Comment by yuange250** [comment]
> 感谢指导，另外，我尝试了不同参数下的Facecrop Dilation Ratio和Height都没有获得完整的头部人像（如上图，头顶部分被截取），请问该如何复现出demo上的效果？

哦哦，做demo我都是把自动裁剪关了手动裁图

**Comment by rahuljustbaat** [comment]
any resolution?

**Comment by progrobe** [comment]
> 有可能是这里引入的： ![image](https://private-user-images.githubusercontent.com/11451501/348602134-5f4d740d-fffa-4705-8c22-6646b6e3380f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MDAxMjMsIm5iZiI6MTczNDQ5OTgyMywicGF0aCI6Ii8xMTQ1MTUwMS8zNDg2MDIxMzQtNWY0ZDc0MGQtZmZmYS00NzA1LThjMjItNjY0NmI2ZTMzODBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDA1MzAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3YTgwOWYzNWUyYzEzZGQ0ZGYxMWNjOTJjYzhkMzQwZGU0N2E3MWRhNTUzYWM5ZjU5NjZkOTBiZTFjYTU2MzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.U6HFkBvdzyB4DwvixKY9tvhCvr3nid0rbQibU8Yt4A4) 可以把这行注掉试试，这个clamp会降低动作幅度，从而降低artifacts出现的概率，但确实会引入更多背景artifacts

请问为什么这个代码会降低动作幅度，以及缓解背景artifacts？我使用的白色、绿色背景样本里也偶尔出现背景失真，但使用之后并没有降低动作幅度或者缓解失真。作者有建议吗，把1.5减小到1是否会更好？
