### ISSUE TITLE
The width and height of the output are inconsistent with the configuration

### ISSUE THREAD

**Issue by yincangshiwei** [BadToBest/EchoMimic#41]
I configured the width and height according to the original image, but the actual result is different. The height is even higher than what I set.
![image](https://github.com/user-attachments/assets/cd28eb57-df45-408b-a209-22940eff6c6c)
![image](https://github.com/user-attachments/assets/d1494ab8-0791-460b-b87c-0045f0a79e4b)

**Comment by JoeFannie** [comment]
Thank you for the feedback. In the inference code, the face is first cropped to a **square** image. Then, it is fed into the pipe for generation. Therefore, to keep the original aspect ratio, it is recommended to set the same value for height and width. Further, we will work on any aspect ratio generation and make it public as soon as possible.
