### ISSUE TITLE
Pose-Driven Error

### ISSUE THREAD

**Issue by yhqqxq** [BadToBest/EchoMimic#45]
![微信截图_20240716013440](https://github.com/user-attachments/assets/ea902f5b-f6ae-49d7-bba7-e113528ec410)

How should this problem be solved?

**Comment by nitinmukesh** [comment]
So inference is working for you but I think failing during output.

Please could you share pip list and are you using it for sample or your own data.

**Comment by yhqqxq** [comment]
ok, The videos, sounds, and pictures I used all come from the assets folder, I just changed the path and name
![微信截图_20240716125547](https://github.com/user-attachments/assets/596d7ae0-fe15-49eb-8864-76a7c0451dbb)

Package                   Version
------------------------- ------------
absl-py                   2.1.0
accelerate                0.32.1
aiofiles                  23.2.1
altair                    5.3.0
annotated-types           0.7.0
antlr4-python3-runtime    4.9.3
anyio                     4.4.0
asttokens                 2.4.1
attrs                     23.2.0
av                        11.0.0
certifi                   2024.7.4
cffi                      1.16.0
charset-normalizer        3.3.2
click                     8.1.7
colorama                  0.4.6
contourpy                 1.2.1
cycler                    0.12.1
decorator                 4.4.2
diffusers                 0.24.0
dnspython                 2.6.1
einops                    0.4.1
email_validator           2.2.0
exceptiongroup            1.2.2
executing                 2.0.1
facenet-pytorch           2.5.0
fastapi                   0.111.1
fastapi-cli               0.0.4
ffmpeg-python             0.2.0
ffmpy                     0.3.2
filelock                  3.15.4
flatbuffers               24.3.25
fonttools                 4.53.1
fsspec                    2024.6.1
future                    1.0.0
gradio                    4.38.1
gradio_client             1.1.0
h11                       0.14.0
httpcore                  1.0.5
httptools                 0.6.1
httpx                     0.27.0
huggingface-hub           0.23.4
idna                      3.7
imageio                   2.34.2
imageio-ffmpeg            0.5.1
importlib_metadata        8.0.0
importlib_resources       6.4.0
ipython                   8.26.0
jax                       0.4.30
jaxlib                    0.4.30
jedi                      0.19.1
Jinja2                    3.1.4
jsonschema                4.23.0
jsonschema-specifications 2023.12.1
kiwisolver                1.4.5
lazy_loader               0.4
lightning-utilities       0.11.4
markdown-it-py            3.0.0
MarkupSafe                2.1.5
matplotlib                3.9.1
matplotlib-inline         0.1.7
mdurl                     0.1.2
mediapipe                 0.10.14
ml-dtypes                 0.4.0
moviepy                   1.0.3
mpmath                    1.3.0
networkx                  3.3
numpy                     1.26.4
omegaconf                 2.3.0
opencv-contrib-python     4.10.0.84
opencv-python             4.10.0.84
opt-einsum                3.3.0
orjson                    3.10.6
packaging                 24.1
pandas                    2.2.2
parso                     0.8.4
pillow                    10.4.0
pip                       24.0
proglog                   0.1.10
prompt_toolkit            3.0.47
protobuf                  4.25.3
psutil                    6.0.0
pure-eval                 0.2.2
pycparser                 2.22
pydantic                  2.8.2
pydantic_core             2.20.1
pydub                     0.25.1
Pygments                  2.18.0
pyparsing                 3.1.2
python-dateutil           2.9.0.post0
python-dotenv             1.0.1
python-multipart          0.0.9
pytz                      2024.1
PyYAML                    6.0.1
referencing               0.35.1
regex                     2024.5.15
requests                  2.32.3
rich                      13.7.1
rpds-py                   0.19.0
ruff                      0.5.2
safetensors               0.4.3
scikit-image              0.24.0
scipy                     1.14.0
semantic-version          2.10.0
setuptools                70.3.0
shellingham               1.5.4
six                       1.16.0
sniffio                   1.3.1
sounddevice               0.4.7
stack-data                0.6.3
starlette                 0.37.2
sympy                     1.13.0
tifffile                  2024.7.2
tokenizers                0.19.1
tomlkit                   0.12.0
toolz                     0.12.1
torch                     2.0.1+cu118
torchaudio                2.2.2
torchmetrics              1.4.0.post0
torchtyping               0.1.4
torchvision               0.15.2+cu118
tqdm                      4.66.4
traitlets                 5.14.3
transformers              4.42.4
typeguard                 4.3.0
typer                     0.12.3
typing_extensions         4.12.2
tzdata                    2024.1
urllib3                   2.2.2
uvicorn                   0.30.1
watchfiles                0.22.0
wcwidth                   0.2.13
websockets                11.0.3
wheel                     0.43.0
zipp                      3.19.2

**Comment by JoeFannie** [comment]
The mismatched length between pose list and image list leads to the error. You can set the length(args.L) to 120 (min size of the two lists).

**Comment by yhqqxq** [comment]
Could you tell me where this args.L is set? 
Also, is the maximum length of all characters only 120?
