### ISSUE TITLE
FPS test (Gradio Configuration)

### ISSUE THREAD

**Issue by oisilener1982** [BadToBest/EchoMimic#47]
12 FPS

https://github.com/user-attachments/assets/d72e76fd-558c-47ec-b383-cf689be99485

24

https://github.com/user-attachments/assets/e982604f-6115-4c8c-bd2e-ca56e36b23ca

40

https://github.com/user-attachments/assets/35e0abb8-3a8c-4bb7-947e-24cc6652bbb5

60

https://github.com/user-attachments/assets/560a12a9-1395-4688-8931-316782c1df73

Source Image:
![Ivana4](https://github.com/user-attachments/assets/a4a20717-1b11-4d64-baff-a991bfdac4f2)

**Comment by oisilener1982** [comment]
12 is so slow
24 is ok
40 is lively
60 too fast

**Comment by JoeFannie** [comment]
Thanks for your evaluation.
