### ISSUE TITLE
Sample Rate Test (Gradio Configuration)

### ISSUE THREAD

**Issue by oisilener1982** [BadToBest/EchoMimic#48]
8000 Sample Rate

https://github.com/user-attachments/assets/ca7b8b46-fc82-4891-815d-8037fbf9afb8

16000

https://github.com/user-attachments/assets/ce3de438-3b60-4881-8c35-ccc6c29b22ac

32000

https://github.com/user-attachments/assets/24f8d760-88af-4700-a3a7-3b32b54e3e9b

48000

https://github.com/user-attachments/assets/96acaa6c-aec6-4c43-81a5-038316ee0b2d

THere is not much difference between all the sample rate from 8000 to 48000
The Generation time is also almost the same no matter what is the sample rate

![Capture2](https://github.com/user-attachments/assets/33c9168f-5c34-4b50-816a-7fb250a8ceb2)

**Comment by JoeFannie** [comment]
Yes, the sample rate are not related with the generation time. In fact, it is the sample rate of the audio file, which determines how we sample the audio wave.
