### ISSUE TITLE
CFG Test (Gradio Configuration)

### ISSUE THREAD

**Issue by oisilener1982** [BadToBest/EchoMimic#49]
1.1 CFG This is lowest setting that works in my test with no error

https://github.com/user-attachments/assets/d4e432e0-9e72-4bdb-98cb-47908f70304c

1.5

https://github.com/user-attachments/assets/caf72c92-c982-4a42-a12c-4cd49fa11fb3

2

https://github.com/user-attachments/assets/3fc78d18-da99-4582-9792-85e1da1e052f

2.5

https://github.com/user-attachments/assets/5bf281d5-757e-4e65-96de-989ebd366084

3

https://github.com/user-attachments/assets/d165ec5d-6916-46ec-8402-d934ab2d3a34

4

https://github.com/user-attachments/assets/ce7bd485-1297-4dae-9fda-52ad7818b224

5

https://github.com/user-attachments/assets/cf19cc51-c55e-4a84-8ea6-74b90870f3b9

7

https://github.com/user-attachments/assets/7521402c-9788-4071-b34b-ff3506c13425

10

https://github.com/user-attachments/assets/6500608c-c157-4c54-be11-4f39124aeeed

**Comment by oisilener1982** [comment]
I personally like CFG 4 or 5. You can also play with this setting, it does not affect the generation time
The lowest settings of 1.1 is not acceptable and the highest CFG 10 is also not good

**Comment by yuange250** [comment]
good job 👍

**Comment by JoeFannie** [comment]
We have found that the current code only supports cfg > 1. We are working on fix this bug. Thank you for ablation study.
