### ISSUE TITLE
Any video tutorial how to install ffmpeg-static?

### ISSUE THREAD

**Issue by oisilener1982** [BadToBest/EchoMimic#5]
Download ffmpeg-static
Download and decompress ffmpeg-static, then

export FFMPEG_PATH=/path/to/ffmpeg-4.4-amd64-static

**Comment by yuange250** [comment]
Sorry for that, can you download the file from the follow link ? 
https://www.johnvansickle.com/ffmpeg/old-releases/ffmpeg-4.4-amd64-static.tar.xz

**Comment by oisilener1982** [comment]
I already have the file and im having difficulty how to properly install. Im not a programmer :(

What is meant by: export FFMPEG_PATH=/path/to/ffmpeg-4.4-amd64-static

**Comment by yuange250** [comment]
OK, is your operating system windows or linux?

Firstliy, copy the full path of ffmpeg-4.4-amd64-static, like /home/XXX/ffmpeg-4.4-amd64-static(linux) or D:/xxxx/ffmpeg-4.4-amd64-static(windows)

Then, here is the easiest way to solve your problem, open the 'infer_audio2vid.py', change the line 32 to your own path:
current:
![1](https://github.com/BadToBest/EchoMimic/assets/11451501/4f9e6619-a75b-4ea4-aba6-7371eabae6bd)
after change:
![2](https://github.com/BadToBest/EchoMimic/assets/11451501/81afa3f9-cd2d-418e-a975-d4d8467f2592)

**Comment by oisilener1982** [comment]
Thanks, i think the above suggestion helped but i have a new error: 

(echomimic) D:\AI\EchoMimic>python -u infer_audio2vid.py
C:\Users\Renel\anaconda3\envs\echomimic\lib\site-packages\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
C:\Users\Renel\anaconda3\envs\echomimic\lib\site-packages\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
please download ffmpeg-static and export to FFMPEG_PATH.
For example: export FFMPEG_PATH=/musetalk/ffmpeg-4.4-amd64-static
Cannot initialize model with low cpu memory usage because `accelerate` was not found in the environment. Defaulting to `low_cpu_mem_usage=False`. It is strongly recommended to install `accelerate` for faster and less memory-intense model loading. You can do so with:
```
pip install accelerate
```
.
Traceback (most recent call last):
  File "infer_audio2vid.py", line 243, in <module>
    main()
  File "infer_audio2vid.py", line 97, in main
    vae = AutoencoderKL.from_pretrained(
  File "C:\Users\Renel\anaconda3\envs\echomimic\lib\site-packages\torch\nn\modules\module.py", line 1173, in to
    return self._apply(convert)
  File "C:\Users\Renel\anaconda3\envs\echomimic\lib\site-packages\torch\nn\modules\module.py", line 779, in _apply
    module._apply(fn)
  File "C:\Users\Renel\anaconda3\envs\echomimic\lib\site-packages\torch\nn\modules\module.py", line 779, in _apply
    module._apply(fn)
  File "C:\Users\Renel\anaconda3\envs\echomimic\lib\site-packages\torch\nn\modules\module.py", line 804, in _apply
    param_applied = fn(param)
  File "C:\Users\Renel\anaconda3\envs\echomimic\lib\site-packages\torch\nn\modules\module.py", line 1159, in convert
    return t.to(
  File "C:\Users\Renel\anaconda3\envs\echomimic\lib\site-packages\torch\cuda\__init__.py", line 284, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by oisilener1982** [comment]
![Capture](https://github.com/BadToBest/EchoMimic/assets/29243313/e134ee40-d1e6-4dbe-85af-b6d9f94465ae)

**Comment by yuange250** [comment]
reinstall torch and torchvision may solve the problem.

pip install torch==2.0.1
pip install torchvision==0.15.2

**Comment by hotdogarea** [comment]
> ```
> pip install accelerate
> ```

我是windows11 python3.10环境下，按照要求安装了对应版本的torch，但我的cuda是12.5的。依然提示这个
  File "C:\Users\Administrator\.conda\envs\echo\lib\site-packages\torch\nn\modules\module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "C:\Users\Administrator\.conda\envs\echo\lib\site-packages\torch\cuda\__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
PS H:\AIaudio_Live\EchoMimic> pip list
Package                Version
---------------------- ------------
accelerate             0.32.1
antlr4-python3-runtime 4.9.3
av                     11.0.0
certifi                2024.7.4
charset-normalizer     3.3.2
colorama               0.4.6
decorator              4.4.2
diffusers              0.24.0
einops                 0.4.1
facenet-pytorch        2.5.0
ffmpeg-python          0.2.0
filelock               3.15.4
fsspec                 2024.6.1
future                 1.0.0
huggingface-hub        0.23.4
idna                   3.7
imageio                2.34.2
imageio-ffmpeg         0.5.1
importlib_metadata     8.0.0
intel-openmp           2021.4.0
Jinja2                 3.1.4
lightning-utilities    0.11.3.post0
MarkupSafe             2.1.5
mkl                    2021.4.0
moviepy                1.0.3
mpmath                 1.3.0
networkx               3.3
numpy                  1.26.4
omegaconf              2.3.0
opencv-python          4.10.0.84
packaging              24.1
pillow                 10.4.0
pip                    24.0
proglog                0.1.10
psutil                 6.0.0
PyYAML                 6.0.1
regex                  2024.5.15
requests               2.32.3
safetensors            0.4.3
setuptools             69.5.1
sympy                  1.13.0
tbb                    2021.13.0
tokenizers             0.19.1
torch                  2.0.1
torchaudio             2.0.2
torchmetrics           1.4.0.post0
torchtyping            0.1.4
torchvision            0.15.2
tqdm                   4.66.4
transformers           4.42.3
typeguard              4.3.0
typing_extensions      4.12.2
urllib3                2.2.2
wheel                  0.43.0
zipp                   3.19.2

**Comment by hotdogarea** [comment]
> ![image](https://private-user-images.githubusercontent.com/11146882/347336622-c55f9b9c-2d4f-4b9c-94ec-7326c6990e4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MDQwNjIsIm5iZiI6MTcyMDYwMzc2MiwicGF0aCI6Ii8xMTE0Njg4Mi8zNDczMzY2MjItYzU1ZjliOWMtMmQ0Zi00YjljLTk0ZWMtNzMyNmM2OTkwZTRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDA5MjkyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2ZTlmYzFjMWIzYjU1ZTY0YTVhY2NmMzIyMGNhNTEzZTI0ZjU3YjlmOGNhZTAxNjA2YjgxMTlmYTM0M2FkMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3H3iqjo06O7ydD8zkyYO4oGHKtEmAYA6lb_4KIbQuVE)
> 
> 我是windows11 python3.10环境下，按照要求安装了对应版本的torch，但我的cuda是12.5的。依然提示这个，安装的时候我用的清华源，是清华源的问题？
> 
> File "C:\Users\Administrator.conda\envs\echo\lib\site-packages\torch\nn\modules\module.py", line 1143, in convert return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking) File "C:\Users\Administrator.conda\envs\echo\lib\site-packages\torch\cuda__init__.py", line 239, in _lazy_init raise AssertionError("Torch not compiled with CUDA enabled") AssertionError: Torch not compiled with CUDA enabled PS H:\AIaudio_Live\EchoMimic> pip list Package Version
> 
> accelerate 0.32.1 antlr4-python3-runtime 4.9.3 av 11.0.0 certifi 2024.7.4 charset-normalizer 3.3.2 colorama 0.4.6 decorator 4.4.2 diffusers 0.24.0 einops 0.4.1 facenet-pytorch 2.5.0 ffmpeg-python 0.2.0 filelock 3.15.4 fsspec 2024.6.1 future 1.0.0 huggingface-hub 0.23.4 idna 3.7 imageio 2.34.2 imageio-ffmpeg 0.5.1 importlib_metadata 8.0.0 intel-openmp 2021.4.0 Jinja2 3.1.4 lightning-utilities 0.11.3.post0 MarkupSafe 2.1.5 mkl 2021.4.0 moviepy 1.0.3 mpmath 1.3.0 networkx 3.3 numpy 1.26.4 omegaconf 2.3.0 opencv-python 4.10.0.84 packaging 24.1 pillow 10.4.0 pip 24.0 proglog 0.1.10 psutil 6.0.0 PyYAML 6.0.1 regex 2024.5.15 requests 2.32.3 safetensors 0.4.3 setuptools 69.5.1 sympy 1.13.0 tbb 2021.13.0 tokenizers 0.19.1 torch 2.0.1 torchaudio 2.0.2 torchmetrics 1.4.0.post0 torchtyping 0.1.4 torchvision 0.15.2 tqdm 4.66.4 transformers 4.42.3 typeguard 4.3.0 typing_extensions 4.12.2 urllib3 2.2.2 wheel 0.43.0 zipp 3.19.2

解决了，不要用清华源，去pytorch官网下载2.4G版本那个torch
https://download.pytorch.org/whl/torch_stable.html
