### ISSUE TITLE
python -u webgui.py --server_port=3000报错误No module named 'moviepy'，moviepy已安装

### ISSUE THREAD

**Issue by italks** [BadToBest/EchoMimic#51]
![image](https://github.com/user-attachments/assets/bde2fc01-1ca7-4fab-b808-f0e946be6788)
运行
`python -u webgui.py --server_port=3000`报错误`ModuleNotFoundError: No module named 'moviepy'`，但是已经安装了，这是怎么回事？
D:\ProgramData\miniconda3\envs\echomimic\lib\site-packages\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
D:\ProgramData\miniconda3\envs\echomimic\lib\site-packages\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
D:\ProgramData\miniconda3\envs\echomimic\lib\site-packages\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
Traceback (most recent call last):
  File "webgui.py", line 24, in <module>
    from moviepy.editor import VideoFileClip, AudioFileClip
ModuleNotFoundError: No module named 'moviepy'
(echomimic) PS C:\Users\italk\EchoMimic> pip install moviepy
Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
Requirement already satisfied: moviepy in d:\programdata\miniconda3\envs\echomimic\lib\site-packages (1.0.3)
Requirement already satisfied: decorator<5.0,>=4.0.2 in d:\programdata\miniconda3\envs\echomimic\lib\site-packages (from moviepy) (4.4.2)
Requirement already satisfied: tqdm<5.0,>=4.11.2 in d:\programdata\miniconda3\envs\echomimic\lib\site-packages (from moviepy) (4.66.4)
Requirement already satisfied: requests<3.0,>=2.8.1 in d:\programdata\miniconda3\envs\echomimic\lib\site-packages (from moviepy) (2.32.3)
Requirement already satisfied: proglog<=1.0.0 in d:\programdata\miniconda3\envs\echomimic\lib\site-packages (from moviepy) (0.1.10)
Requirement already satisfied: numpy>=1.17.3 in d:\programdata\miniconda3\envs\echomimic\lib\site-packages (from moviepy) (1.24.4)
Requirement already satisfied: imageio<3.0,>=2.5 in d:\programdata\miniconda3\envs\echomimic\lib\site-packages (from moviepy) (2.34.2)
Requirement already satisfied: imageio-ffmpeg>=0.2.0 in d:\programdata\miniconda3\envs\echomimic\lib\site-packages (from moviepy) (0.5.1)
Requirement already satisfied: pillow>=8.3.2 in d:\programdata\miniconda3\envs\echomimic\lib\site-packages (from imageio<3.0,>=2.5->moviepy) (10.4.0)
Requirement already satisfied: setuptools in d:\programdata\miniconda3\envs\echomimic\lib\site-packages (from imageio-ffmpeg>=0.2.0->moviepy) (69.5.1)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\programdata\miniconda3\envs\echomimic\lib\site-packages (from requests<3.0,>=2.8.1->moviepy) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in d:\programdata\miniconda3\envs\echomimic\lib\site-packages (from requests<3.0,>=2.8.1->moviepy) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\programdata\miniconda3\envs\echomimic\lib\site-packages (from requests<3.0,>=2.8.1->moviepy) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in d:\programdata\miniconda3\envs\echomimic\lib\site-packages (from requests<3.0,>=2.8.1->moviepy) (2024.7.4)
Requirement already satisfied: colorama in d:\programdata\miniconda3\envs\echomimic\lib\site-packages (from tqdm<5.0,>=4.11.2->moviepy) (0.4.6)

**Comment by JoeFannie** [comment]
这种一般是装在了不同的环境，看看运行EchoMimic的虚拟环境和安装的虚拟环境是不是一个

**Comment by italks** [comment]
使用conda新建的虚拟环境echomimic，截图可以看到运行的时候也是在echomimic环境下，安装的依赖也是在这个下面，但是运行报错

**Comment by italks** [comment]
使用阿里云镜像安装的问题，切换到清华源没事了
