### ISSUE TITLE
能不能提供提供一个驱动完整图片的功能？或者提供参数只驱动头部区域运动，现在512*512的边缘会运动，使用者无法合成原大小视频

### ISSUE THREAD

**Issue by sunbin728** [BadToBest/EchoMimic#52]
能不能提供提供一个驱动完整图片的功能？或者提供参数只驱动头部区域运动，现在512*512的边缘会运动，使用者无法合回原大小的视频，无法对齐，会有明显分隔

**Comment by Galleons2029** [comment]
同问，调整过多组参数仍然没有demo里的那种效果  貌似是因为面部锁定的缘故？

**Comment by cindylaii** [comment]
同問。臉的效果非常好，但是跑完切到只剩下臉，不符合需求。
有什麼方法能連身體也一起產出到video裡？

**Comment by cindylaii** [comment]
> 同問。臉的效果非常好，但是跑完切到只剩下臉，不符合需求。 有什麼方法能連身體也一起產出到video裡？

自問自答：Facecrop Dilation Ratio設成1，出來的效果比較好一些，至少沒有裁得很小

**Comment by JoeFannie** [comment]
这个已经在开发了～有较好的结果我们会放出来～
