### ISSUE TITLE
能否提供多卡推理

### ISSUE THREAD

**Issue by jinghong-6** [BadToBest/EchoMimic#53]
能否提供自适应多卡推理功能，我在四卡机器上运行，只使用了第一张显卡，速度不够理想

**Comment by yuange250** [comment]
抱歉这个与现有算法基础有冲突，改造量较大，短期内可能很难支持

**Comment by JoeFannie** [comment]
加速的模型马上就要发布了，速度会有明显提升，预计加速10倍
