### ISSUE TITLE
About FID/FVD metric

### ISSUE THREAD

**Issue by Vincent-luo** [BadToBest/EchoMimic#56]
Thanks for your great work!
I have a question about the model evaluation. Many related works report FID/FVD metrics for their models, but they often lack specific details about the evaluation process. I'd like to know whether you calculated FID/FVD on the training split or the test split, and how many images/videos you generated when computing these metrics. If you could provide more specific evaluation details, it would be helpful for fair comparisons between models.

**Comment by JoeFannie** [comment]
We will consider adding the details to our paper. Thanks for your advise.
