### ISSUE TITLE
How is 10x acceleration achieved?

### ISSUE THREAD

**Issue by FacePoluke** [BadToBest/EchoMimic#60]
Thank you for your amazing work. I am curious about how the 10x acceleration is achieved. Can you give me the details?

**Comment by oisilener1982** [comment]
i also want to know this. Inference is still the same for me after updating

**Comment by rammiah** [comment]
> i also want to know this. Inference is still the same for me after updating

only pose-driven accelerated model released, audio-driven model is still slow

**Comment by oisilener1982** [comment]
Thanks for the update. I mainly use audio driven

**Comment by LiamTTT** [comment]
It seems to be some kind of improved LCM-Like method.

**Comment by JoeFannie** [comment]
It is a step-distill technique proposed by our previous work in ECCV2024.

**Comment by leemengtw** [comment]
> It is a step-distill technique proposed by our previous work in ECCV2024.

@JoeFannie great work from the team! Sorry for replying in this closed ticket but just want to confirm is the [SlimFlow](https://arxiv.org/abs/2407.12718) the previous work the team is using to do the accleration?

**Comment by wangxihao** [comment]
> It is a step-distill technique proposed by our previous work in ECCV2024.
Thank you! Which specific article are you referring to?

**Comment by wangxihao** [comment]
> It is a step-distill technique proposed by our previous work in ECCV2024.

Thank you! Which specific article are you referring to?
