### ISSUE TITLE
Audio driven acceleration not possible?

### ISSUE THREAD

**Issue by kashishnaqvi101** [BadToBest/EchoMimic#62]
Hey, I tried to run accelerated models, it did not run for pose script, my installations are recent. But I am eager to run it for audio driven inference. Can you tell us by when would it be released?

**Comment by theZaX** [comment]
Same this would be excellent for us

**Comment by oisilener1982** [comment]
I also need this one. Hope devs would be able to accelerate Audio Driven

**Comment by JoeFannie** [comment]
Audio accelerated models and pipes are released. Please try it.
