### ISSUE TITLE
如何平衡latent上的mse loss 和 pixel空间的spatial loss

### ISSUE THREAD

**Issue by XuankeShi** [BadToBest/EchoMimic#63]
论文提到了一个权重, 关于这两部分的loss权重, 想咨询下是否有经验可以借鉴.  另外,在pixel空间的spatial loss, 在vgg perception loss 和 L2 loss的权重是否有相关的配置.

**Comment by JoeFannie** [comment]
这个我们后续会根据paper投稿情况给出详细细节。
