### ISSUE TITLE
测试了最新的更新，项目说速度提升10X以上，测试结果，基本上无任何提升

### ISSUE THREAD

**Issue by tgdtu** [BadToBest/EchoMimic#66]
测试了最新的更新，项目说速度提升10X以上，测试结果，基本上无任何提升，大家有测试结果吗？

**Comment by lymhust** [comment]
测试代码发出来看一下，或者加微信群进群讨论一下。

**Comment by tgdtu** [comment]
邮件已收到，谢谢！冶专涂国栋。

**Comment by tgdtu** [comment]
@lymhust 群怎么加？

**Comment by lymhust** [comment]
Git readme主页，有个微信图标，点开，扫右边小助手的二维码，让他拉你进讨论群。

**Comment by tgdtu** [comment]
@lymhust 加了，要等统一处理，谢谢
