### ISSUE TITLE
Will publish a gradio app that has all the features you presented in paper?

### ISSUE THREAD

**Issue by FurkanGozukara** [BadToBest/EchoMimic#7]
that would be great

**Comment by yuange250** [comment]
We are considering developing a ComfyUI node, and we will inform you as soon as the development is completed.：）

**Comment by FurkanGozukara** [comment]
@yuange250 comfyui is being very limited audience. please make gradio as well ty

**Comment by nitinmukesh** [comment]
Yes please gradio based UI

**Comment by JoeFannie** [comment]
We are working on a hf demo via gradio. The corresponding code can be released if it is necessary.

**Comment by FurkanGozukara** [comment]
> We are working on a hf demo via gradio. The corresponding code can be released if it is necessary.

Cloneable hf demo would work. Just add all features ty
