### ISSUE TITLE
Whats the difference between this and aniportrait?

### ISSUE THREAD

**Issue by G-force78** [BadToBest/EchoMimic#70]
https://github.com/Zejun-Yang/AniPortrait

**Comment by oisilener1982** [comment]
Echomimic works with 10gb RTX 3080 and Aniportrait does not

**Comment by oisilener1982** [comment]
Echomimic is way better. I can run echomimic with just 10gb vram in RTX 3080

**Comment by oisilener1982** [comment]
Echomimic works while Aniportrait does not unless you have lots of vram

**Comment by G-force78** [comment]
> Echomimic works while Aniportrait does not unless you have lots of vram

Echomimic takes up a massive amount of storage, 75+GB
