### ISSUE TITLE
Stitch the head back to the body

### ISSUE THREAD

**Issue by oisilener1982** [BadToBest/EchoMimic#75]
Is there a way to stitch the head back to the body just like in Sadtalker?

![Capture](https://github.com/user-attachments/assets/8ae490a1-5719-409a-82ac-5f7075d6894d)

**Comment by G-force78** [comment]
synctalk manages to do that too somehow
https://github.com/ZiqiaoPeng/SyncTalk

**Comment by JoeFannie** [comment]
It is under development and will be released ASAP.
