### ISSUE TITLE
能不能不要裁切上传的图片？

### ISSUE THREAD

**Issue by redstoneleo** [BadToBest/EchoMimic#81]
我上传了上半身的照片，结果裁切了主要只有头部，不是我想要的，能不能不要裁切上传的图片？

**Comment by JoeFannie** [comment]
裁剪为了效果是必须的。我们后续会开发paste back功能，再把crop的人脸贴回去。

**Comment by redstoneleo** [comment]
最好有一个不动原图的功能，比如https://huggingface.co/spaces/vinthony/SadTalker的full这个选项
![image](https://github.com/user-attachments/assets/ac4bea28-b471-4210-aff7-fec11be0bfac)
