### ISSUE TITLE
上传四分钟的音频合出来好像只有前面10s，后面的图片就不会动了

### ISSUE THREAD

**Issue by redstoneleo** [BadToBest/EchoMimic#82]
测试平台：https://www.modelscope.cn/studios/BadToBest/BadToBest

**Comment by O-O1024** [comment]
可能是 video_length 太小了

**Comment by JoeFannie** [comment]
调整video_length = fps * time，例如4分钟=240s fps=24，video length调整到240s或者5760帧

**Comment by redstoneleo** [comment]
这个感觉是可以根据上传的音频时长自动计算的吧，为什么也要用户手动计算后输入呢？
