### ISSUE TITLE
发现两个问题

### ISSUE THREAD

**Issue by nicevlhjfihtqngkldl** [BadToBest/EchoMimic#85]
问题1. 我合成的视频长度是1分钟,但是到50秒的时候,画面就不动了.这个哪里设置呢?
问题2.  我提供的图片长宽都超过512,但是最终的视频分辨率大小是512X512,视频分辨率请问怎么调整呢?

**Comment by yuange250** [comment]
1. L参数的设置问题，现在默认最大1200帧，也就是50s左右
2. 现在模型只能对512有比较好的效果，所以做了强制resize，调整分辨率之后效果可能不会太好

**Comment by xiao-keeplearning** [comment]
你好，问下这个L参数可以调大么，调大该参数会不会导致效果变差

**Comment by ldavis9000aws** [comment]
I'd also like to know if the L parameter can be increased.
