### ISSUE TITLE
如何使用多GPU推理

### ISSUE THREAD

**Issue by ppx0001** [BadToBest/EchoMimic#86]
现在只能使用GPU0进行推理，还有多个空闲GPU

**Comment by yuange250** [comment]
多卡、流式输出在现行的算法框架下都是比较难改造的点。。。要实现这类工程改造需要从源头对算法框架进行重构，难度比较大，也很难保证是否能实现

**Comment by FucK5t4r** [comment]
> 现在只能使用GPU0进行推理，还有多个空闲GPU

可以简单在推理的时候加一个mapredece多线程手动分配卡，因为echomimic不涉及自回归推理，所以理论实现起来也不复杂
