### ISSUE TITLE
如果video_length超过face_mask_tensor的长度会崩溃

### ISSUE THREAD

**Issue by XeoOuYang** [BadToBest/EchoMimic#93]
infra_ audio2vid acc. py中，如果video_length超过face_mask_tensor的长度，会报错。因为在推理过程中pose_latents_cond = torch.cat([face_locator_tensor[:, :, c] for c in new_context]).to(device)的c会越界，从而导致崩溃。

**Comment by XeoOuYang** [comment]
acc与之前区别是arg.L默认1200和240的差异

**Comment by JoeFannie** [comment]
多谢，这个问题在后续的版本会修复
