### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './pretrained_weights/denoising_unet_acc.pth'

### ISSUE THREAD

**Issue by oisilener1982** [BadToBest/EchoMimic#95]
infer_audio2vid.py is working Fine
infer_audio2vid_acc.py have this error

mid_block.attentions.0.transformer_blocks.0.norm2.bias, conv_norm_out.weight, conv_norm_out.bias, conv_out.weight, conv_out.bias']
Traceback (most recent call last):
  File "infer_audio2vid_acc.py", line 257, in <module>
    main()
  File "infer_audio2vid_acc.py", line 146, in main
    torch.load(config.denoising_unet_path, map_location="cpu"),
  File "C:\Users\Renel\anaconda3\envs\echomimic\lib\site-packages\torch\serialization.py", line 997, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\Renel\anaconda3\envs\echomimic\lib\site-packages\torch\serialization.py", line 444, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\Renel\anaconda3\envs\echomimic\lib\site-packages\torch\serialization.py", line 425, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './pretrained_weights/denoising_unet_acc.pth'

**Comment by nitinmukesh** [comment]
You need to download the additional weights. 
https://huggingface.co/BadToBest/EchoMimic

[denoising_unet_acc.pth](https://huggingface.co/BadToBest/EchoMimic/blob/main/denoising_unet_acc.pth)
[denoising_unet_pose_acc.pth](https://huggingface.co/BadToBest/EchoMimic/blob/main/denoising_unet_pose_acc.pth)
[motion_module_acc.pth](https://huggingface.co/BadToBest/EchoMimic/blob/main/motion_module_acc.pth)
[motion_module_pose_acc.pth](https://huggingface.co/BadToBest/EchoMimic/blob/main/motion_module_pose_acc.pth)

**Comment by oisilener1982** [comment]
![Capture](https://github.com/user-attachments/assets/8cb14b40-378f-41f5-ac9c-8717873e5152)

denoising_unet_acc.pth is present in the pretrained weights

**Comment by nitinmukesh** [comment]
@oisilener1982 

Please see my earlier comment

**Comment by oisilener1982** [comment]
Thanks again. Its working now.
